"""
===========================================================
389. Find the Difference
===========================================================

🧩 Problem:
You are given two strings `s` and `t` where `t` is generated by **shuffling** `s` and adding **one extra character**.  

Return the **extra character** in `t`.

-----------------------------------------------------------
Examples:
-----------------------------------------------------------
Input:  s = "abcd", t = "abecd"
Output: "e"

Input:  s = "", t = "y"
Output: "y"

-----------------------------------------------------------
Algorithm — XOR Trick:
-----------------------------------------------------------
Idea:

1. XOR all characters in `s` and `t`.  
2. All common characters cancel each other out (x ^ x = 0).  
3. The remaining value is the ASCII of the extra character.  
4. Convert it back to character with `chr()`.

Key Insight:
- XOR is commutative and associative, so the order of characters doesn’t matter.  
- Time complexity O(n), space complexity O(1).

-----------------------------------------------------------
⏱ Time Complexity:   O(n)
💾 Space Complexity:  O(1)
-----------------------------------------------------------
"""

# ------------------------------------
# Solution: XOR Trick
# ------------------------------------
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        xor = 0

        for c in t:
            xor ^= ord(c)
        for c in s:
            xor ^= ord(c)

        return chr(xor)

# ------------------------------------
# Driver Test
# ------------------------------------
if __name__ == "__main__":

    sol = Solution()

    print(sol.findTheDifference("abcd", "abecd"))  # Expected Output: "e"
    print(sol.findTheDifference("", "y"))          # Expected Output: "y"
    print(sol.findTheDifference("aabbcc", "abcabcx")) # Expected Output: "x"